### ISSUE TITLE
TFRS - Add Redis Service for Local Development

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#1078]
**Description**:
Set up a Redis instance in the TFRS local development `docker-compose` file. The Redis instance will simulate the available balance cache for organization IDs with fake data. This setup allows for local development and testing of TFRS without needing access to the LCFS environment.

**Purpose**:
To enable testing and development of TFRS without needing access to LCFS by using a local Redis instance with mock data representing available balances for compliance reporting.

**Development Requirements**:
- [ ] Add a Redis service to the TFRS `docker-compose` file.
- [ ] Pre-populate the Redis instance with temporary fake data for available balances using organization IDs and compliance periods.
- [ ] Ensure TFRS can query Redis locally to fetch the available balances for testing purposes.

**Acceptance Criteria**:
- Redis instance is running in local development using `docker-compose`.
- Redis contains fake data for organization IDs and compliance periods, simulating available balances.
- TFRS can successfully query the Redis cache during local development to fetch the mock data.

**Additional Context**:
- This setup is only for local development; no connection to LCFS is required.
- Example data for Redis might include random organization IDs and compliance unit amounts for testing.

### **Add redis to `docker-compose.yml` for TFRS:**

```yaml
  redis:
    image: redis:6-alpine
    container_name: tfrs_redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
```

### **Redis Setup with Fake Data**:

You can pre-load the Redis instance with some fake data for local development using a simple script:

```bash
redis-cli <<EOF
SET organization_1_compliance_2024 10000
SET organization_2_compliance_2024 5000
EOF
```
