### ISSUE TITLE
LCFS - Create CI/CD pipeline for tests implemented in our pipeline, have the test approvals show up in checks in PRs

### ISSUE THREAD

**Issue by AlexZorkin** [bcgov/lcfs#619]
**Description:**

We would like to set up a comprehensive CI/CD pipeline using GitHub Actions that runs Cypress end-to-end (e2e) tests, backend Pytests, and frontend unit tests. This pipeline should automatically execute these tests when a pull request (PR) is created, and the results (pass/fail) should appear as checks in the PR. PRs should not be mergeable if any tests fail.

**Acceptance Criteria:**

- **Given** a PR is created, **when** the pipeline runs, **then** Cypress e2e tests, backend Pytests, and frontend unit tests should be executed.
- **Given** the tests are executed, **when** they pass or fail, **then** the results should appear as checks in the PR.
- **Given** a PR has failing tests, **when** the checks appear, **then** the PR should not be mergeable until all tests pass.

**Development Checklist:**

1. **Set Up GitHub Actions Workflow:**
   - Create a new workflow file (e.g., `.github/workflows/ci.yml`).
   - Define jobs for running Cypress e2e tests, backend Pytests, and frontend unit tests.

2. **Configure Cypress e2e Tests:**
   - Install necessary dependencies.
   - Define a job in the workflow to run Cypress tests.
   - Ensure Cypress tests are executed in a suitable environment (e.g., headless browser).

3. **Configure Backend Pytests:**
   - Install necessary dependencies.
   - Define a job in the workflow to run Pytests.
   - Ensure the backend environment is correctly set up (e.g., database connections, environment variables).

4. **Configure Frontend Unit Tests:**
   - Install necessary dependencies.
   - Define a job in the workflow to run frontend unit tests.
   - Ensure the frontend environment is correctly set up (e.g., Node.js, npm).

5. **Set Up PR Checks:**
   - Ensure the workflow file includes conditions to mark the PR as mergeable only if all tests pass.
   - Configure the GitHub repository settings to enforce the passing of these checks before allowing merges.

6. **Testing and Validation:**
   - Test the CI/CD pipeline by creating test PRs.
   - Validate that the test results appear correctly as checks in the PRs.
   - Confirm that PRs with failing tests are not mergeable.

**Notes:**

- Ensure proper handling of environment variables and secrets within GitHub Actions.
- Consider using GitHub Actions caching to speed up the pipeline execution.
- Document the CI/CD pipeline setup and provide instructions for developers on how to troubleshoot test failures.

---

### Example GitHub Actions Workflow File (ci.yml)

```yaml
name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  backend-tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Pytests
        run: pytest
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results
          path: test-results/

  frontend-tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run frontend unit tests
        run: npm test
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: frontend-test-results
          path: test-results/

  cypress-tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install dependencies
        run: npm install
      - name: Run Cypress tests
        run: npx cypress run
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: cypress/results/

  checks:
    runs-on: ubuntu-latest
    needs: [backend-tests, frontend-tests, cypress-tests]
    steps:
      - name: Check test results
        run: |
          if [ -d test-results/ ]; then
            echo "Backend tests passed"
          else
            echo "Backend tests failed"
            exit 1
          fi
          if [ -d frontend-test-results/ ]; then
            echo "Frontend tests passed"
          else
            echo "Frontend tests failed"
            exit 1
          fi
          if [ -d cypress-results/ ]; then
            echo "Cypress tests passed"
          else
            echo "Cypress tests failed"
            exit 1
          fi
```
